### PR TITLE
Twig extension as parameter in service file

### PR DESCRIPTION
**Pull request by rlavolee**
- twig extension as parameter
- allow easy class overriding

### CODE REVIEW

**Comment by richsage** [comment]
@pablodip see [this](https://github.com/symfony/symfony/pull/14070) - thoughts going forward?

**Comment by pablodip** [comment]
"When someone wants to change a service, just changing the class name is rarely enough: the new service probably have some different constructor arguments, ... Or put another way, overriding a service by just changing the class name of a service is a very rare use case."

Yeah, it makes no sense to override a service only by changing the class.

**Comment by rlavolee** [comment]
According to the [Symfony's doc](http://symfony.com/doc/current/cookbook/bundles/override.html#services-configuration), it's relevant

**Comment by pablodip** [comment]
It's going to be changed: https://github.com/symfony/symfony/issues/11881

**Pull request closed without merging**
