### PR TITLE
Add swedish & finnish translations

### PR DESCRIPTION
**Pull request by AntoineLemaire**

### CODE REVIEW

**Comment by sampart** [comment]
Thanks for contributing, @AntoineLemaire!  It's much appreciated.

**Comment by sampart** [comment]
Do you need me to tag a release?

**Comment by AntoineLemaire** [comment]
That would be nice! I'm using my fork actually ^^

Many thanks

**Comment by sampart** [comment]
No probs - here you go: https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle/releases/tag/v1.2.1

**Pull request merged**
