### PR TITLE
Improve the travis configuration

### PR DESCRIPTION
**Pull request by stof**
- test against more PHP versions, including PHP 7 and HHVM
- remove testing against Symfony 2.2 as it is not supported by the bundle anymore
- add testing against newer versions of symfony than 2.3
- switch to the faster container-based infrastructure on Travis
- persist the composer cache between builds

### CODE REVIEW

**Comment by pablodip** [comment]
This isn't working on Travis: https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle/pull/121

PS: Do you know why pull requests on Github are not linked to Travis?

**Comment by stof** [comment]
@pablodip the builds are working on Travis, but the status is not set. This is generally caused by the fact that they don't have an OAuth token for someone with write access to the repo, to authenticate for the commit status API.
this is likely related to the permission changes they had to do in June: http://blog.travis-ci.com/2015-06-18-reauthorization-required-due-to-github-api-changes/ You need to go to Travis and authenticate again so that they renew your token.

**Comment by stof** [comment]
and I updated the PR to fix the syntax error in the Yaml file

**Comment by pablodip** [comment]
I've just given permissions to Travis. Thanks for the info!

Tests are only passing with php 5.6 and symfony 2.3. Is that expected? https://travis-ci.org/whiteoctober/WhiteOctoberPagerfantaBundle/builds/78013250

**Comment by stof** [comment]
Well, your bundle was not tested with recent Symfony versions before, and it looks like your test project has an issue with them

**Comment by stof** [comment]
I know what it is: your controller is trying to change the locale, but it does it too late and changing the locale in the Request has no effect on the translator anymore as it is already initialized (in 2.3, the translator locale was initialized only on the first usage of the translator). I will fix it

**Comment by stof** [comment]
@pablodip looks like they still don't have the necessary permission. Maybe your organization uses third-party access control and blocks Travis, so that your token does not allow them to make the API call

**Comment by pablodip** [comment]
I've just sent an authorisation request to @whiteoctober. @richsage could you possibly have a look?

Thanks a lot @stof!

**Comment by richsage** [comment]
@pablodip just seen it - need to confirm internally (because it gives Travis access to all private repos within the organisation) but will let you know ASAP :)

**Comment by stof** [comment]
@richsage The scopes used by travis-ci.org only give them basic info about the repos, but it does not get access to the content of the repo. Only travis-ci.com is getting full access to private repos, but this is a separate application.
See http://docs.travis-ci.com/user/github-oauth-scopes/

**Comment by sampart** [comment]
I've now approved the access request for Travis.  Sorry it took so long!  And thanks @stof for the detailed explaination.

**Pull request merged**
