### PR TITLE
[WIP] Enable Symfony 3.0 support

### PR DESCRIPTION
**Pull request by trq**

### CODE REVIEW

**Comment by trq** [comment]
All tests are passing at this point. Can this be merged?

**Comment by pablodip** [comment]
Could you possibly make tests run against Symfony 3.0 on the travis config file? https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle/blob/master/.travis.yml

**Comment by sstok** [comment]
The PagerfantaExtension uses the Request service which is deprecated.
https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle/blob/master/Twig/PagerfantaExtension.php#L111 

So this should not be merged yet.

The tests that should catch this are not run by Travis :scream: 
https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle/blob/master/TestsProject/src/WhiteOctober/PagerfantaTestBundle/Tests/Controller/PagerfantaControllerTest.php

https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle/blob/master/phpunit.xml.dist#L6
This doesn't seem to execute the TestsProject folder.

**Comment by mychiara** [comment]
@sstok The replacement of the request service is fairly easy. Just use the 'request_stack' service and getMasterRequest(). That should fix the problem. 
More on the topic: http://symfony.com/blog/new-in-symfony-2-4-the-request-stack

**Comment by sstok** [comment]
@mychiara I know ;) also did this in a project of mine.

https://github.com/rollerworks/datagrid-bundle
I use a special RequestProvider adapter to support both.

https://github.com/rollerworks/datagrid-bundle/blob/master/src/Extension/Symfony/EventSubscriber/RequestSubscriber.php
https://github.com/rollerworks/datagrid-bundle/blob/master/src/Extension/Symfony/RequestUriProviderByListener.php (this can actually be simplified to use the container and get the service, this was done to "pleas" SensioInsight).

https://github.com/rollerworks/datagrid-bundle/blob/master/src/Extension/Symfony/RequestUriProviderByRequestStack.php

https://github.com/rollerworks/datagrid-bundle/blob/master/src/Extension/Symfony/ColumnTypeExtension/ActionTypeExtension.php#L48

**Comment by Raphy** [comment]
Merging this PQ could be nice for developers testing Symfony3.
That's my case... I'm « training » with Symfony3 and I would to paginate my testing app with this bundle but the dependencies are in conflict with the environment.

What should I do ? Abandon the idea to use this bundle and go for another one ?

**Comment by pablodip** [comment]
Done on #130

**Pull request merged**
