### PR TITLE
Update bundle configuration for Symfony 4.2 change

### PR DESCRIPTION
**Pull request by mbabker**

### CODE REVIEW

**Comment by sampart** [comment]
Thanks for contributing, @mbabker; much appreciated!  Do you need a release made for this?

**Comment by mbabker** [comment]
> Do you need a release made for this?

I don't need a release anytime urgently, this particular change won't be an issue until Symfony 5 comes around.

**Comment by lxregistry** [comment]
could you release these changes, because in Symfony 4.2 it produce warnings

**Comment by sampart** [comment]
Sure thing, @lxregistry.  This is now in release v1.2.3: https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle/releases/tag/v1.2.3  Thanks for the feedback.

**Comment by lxregistry** [comment]
thank you, could you publish it to packagist.org to be available via composer

**Pull request merged**
