### PR TITLE
Enable Symfony 3.0 support

### PR DESCRIPTION
**Pull request by sstok**
|Q            |A      |
|---          |---    |
|Bug Fix?     |n      |
|New Feature? |yes    |
|BC Breaks?   |n      |
|Deprecations?|n      |
|Tests Pass?  |Not yet|
|Fixed Tickets|#127   |
|License      |MIT    |

This replaces #127 (I kept the original commit) 

Todo:

- [x] add BC layer for the request
- [x] Fix YAML syntax

### CODE REVIEW

**Comment by sstok** [comment]
Ready :+1:

**Comment by pablodip** [comment]
Fantastic!

Symfony 2.3 is failing on Travis though: https://travis-ci.org/whiteoctober/WhiteOctoberPagerfantaBundle/jobs/95166944

The rest is passing: https://travis-ci.org/whiteoctober/WhiteOctoberPagerfantaBundle: https://travis-ci.org/whiteoctober/WhiteOctoberPagerfantaBundle/builds/95166937

**Comment by sstok** [comment]
Lets see if it works now.

**Comment by pablodip** [comment]
Nice!

Can you think of anything which might make this change backwards incompatible or is it totally mergable?

**Comment by sstok** [comment]
It's backward compatible :+1: so you can safely merge this.

**Comment by kironet** [comment]
So, how to install pagerfanta for sf 3.0?
After composer require white-october/pagerfanta-bundle
I got [error.txt](https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle/files/53955/error.txt)

Thanks

**Pull request merged**
